### ISSUE TITLE
[Нововведение] Реализовать книжный кейс

### ISSUE THREAD

**Issue by DraimCiDo** [Server-Eclipse/Survival#20]
**Опишите что бы вы хотели добавить**
в книжном кейсе нету предметов

**Скриншоты**
![image](https://github.com/user-attachments/assets/856a445a-1959-4591-b3ab-cc7987764703)

**Comment by Armagidosha** [comment]
![DvMHwFYLVHlZe-ezgif com-webp-to-gif-converter](https://github.com/user-attachments/assets/80a909c6-f95a-413d-ad60-77d517d066d4)

**Comment by DraimCiDo** [comment]
Все зачарование будут браться из #46

**Comment by DraimCiDo** [comment]
# В книжнем кейсе будет разделение на категории:
### Плохие чары:
- Проклятие безобидности
- Проклятие голода
- Проклятие неизменчивости
- Проклятие неразрушимости
- Проклятие неудачи
- Проклятие утраты
- Проклятие несьемности
### Хорошие чары:
- Везение
- Боец
- Финальный удар
- Бегство
- Уничтожитель Края
- Кубизм
### Лучшие чары:
- Телекинез
- Мудрость
- Венозное копание
-

**Comment by DraimCiDo** [comment]
Кейс полностью реализован.
