### ISSUE TITLE
[Баг] Неработоспобный плагин AE

### ISSUE THREAD

**Issue by DraimCiDo** [Server-Eclipse/Survival#45]
**Опишите баг**
Проблема с плагином AdvancedEnchantments.

**Как вы его получили**
Сделайте более подробные шаги:
1. Взял в руку зачарование.
2. Нажал ПКМ в левой руке
3. Спамит ошибка в консоли

**Ожидаемый исход**
Рабочий плагин.

**Скриншоты**
![image](https://github.com/user-attachments/assets/42b756a6-c928-4a40-842a-62816c41457f)

**Comment by DraimCiDo** [comment]
Решение бага - #46

**Comment by Sfirut** [comment]
https://www.spigotmc.org/resources/1-17-1-21-1-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90create-custom-enchantments-%E2%9C%85.43058/

**Comment by Sfirut** [comment]
Автор плагина добавил поддержку новой версии, исправил баг.

**Comment by DraimCiDo** [comment]
Плагин обновлен и добавлен на режим.
