### ISSUE TITLE
[Нововведение] Замена плагина AdvancedEnchantments на EcoEnchants

### ISSUE THREAD

**Issue by DraimCiDo** [Server-Eclipse/Survival#46]
**Опишите что бы вы хотели добавить**
Изменение старого плагина на более лучшую версию.

**Ссылка на плагин**
[Плагин](https://www.spigotmc.org/resources/50-sale-%E2%8C%9B-ecoenchants-%E2%AD%95-250-enchantments-%E2%9C%85-create-custom-enchants-%E2%9C%A8-essentials-cmi-support.79573/)

**Скриншоты**
![image](https://github.com/user-attachments/assets/1a62d4d3-6210-41ee-8d50-a4f76bf4d2d8)

**Comment by DraimCiDo** [comment]
Относится к #45

**Comment by DraimCiDo** [comment]
- Плагин переведён.
- Все зачарования переведены.

**Comment by DraimCiDo** [comment]
Отключены зачарования для выпадание как лут

**Comment by DraimCiDo** [comment]
# Весь список зачарований по редкости:
### Обычный
- Везение
- Интроверт
- Телекинез (Добавить в донат-книги)
- Убой
- Удушающий приём
### Необычный
- Боец
- Воздушный поцелуй
- Зеленый пальчик
- Колдовство
- Критовая удача
- Мудрость (Добавить в донат-книги)
- Обогащенное покрытие
- Первая кровь (Добавить в донат-книги)
- Приключенец
- Рыболов
- Старатель
- Столяр
- Уничтожить края
- Финальный удар (Добавить в донат-книги)
- Химик
### Редкий
- Бегство
- Вампиризм (Добавить в донат-книги)
- Венозное копание (Добавить в донат-книги)
- Голиаф
- Дровосек
- Искра
- Кофеинизированный
- Кубизм
- Мощь
- Невидимость
- Ниндзя
- Оглушение
- Охотник за головами
- Охотник на Боссов
- Перегрузка
- Световая вспышка
- Сильные руки
- Стальная струна
- Стойкость
- Усиленый крит
- Фейверк бесконечности
- Чрезвычайность
### Эпический
- Адреналин
- Арканная защита
- Быстрая натяжка (Добавить в донат-книги)
- Виверна (Добавить в донат-книги)
- Контр-атака (Добавить в донат-книги)
- Ловкость
- Месть Ада
- Месть Края
- Переломный удар
- Побег
- Призрак
- Скольжение
- Снайпер
- Тор
- Шалкеровое безумие
- Ядовитый плющ
### Легендарный
- Абразия
- Адский шахтер (Добавить в донат-книги)
- Адское касание (Добавить в донат-книги)
- Вредный
- Живучесть
- Замораживание
- Заражение
- Кровотечение (Добавить в донат-книги)
- Метаболизм
- Нептун
- Отточенность
- Перо
- Помутнение в глазах
- Ранение (Добавить в донат-книги)
- Тройной выстрел
- Трудяга
- Убийственный разрез
- Урожай
- Экскавация (Добавить в донат-книги)
- Сила света
- Проклятие безобидности
- Проклятие голода
- Проклятие неизменчивости
- Проклятие неразрушимости
- Проклятие неудачи
### Особый
- Рывок
- Аура
- Взрывная добыча (Добавить в донат-книги)
- Замешательство (Добавить в донат-книги)
### Очень особенный
- Автопочинка (Добавить в донат-книги)
- Варп-двигатель (Добавить в донат-книги)
- Один за всех
- Превосходство
- Хранитель (Добавить  в донат-книги)

**Comment by DraimCiDo** [comment]
Реализована продажа уник.зачарований в /dshop

**Comment by DraimCiDo** [comment]
Плагин готов к работе.

**Comment by Sfirut** [comment]
Advanced Enchantments намного больше удовлетворяет задачам из-за более понятной системы монетизации проекта за счёт покупки рандомной книги, большей свободы в части разработки своих кастомных книг + уже разработанного большого пула книг, исправленных и дополненных вместе с игроками. Если AE заработает, то надо его возвращать

**Comment by DraimCiDo** [comment]
Убран EcoEnchants, вновь добавлен Advanced Enchantments
