### ISSUE TITLE
[Баг] Кейс С Квинтами(Донат валютой) не выдаёт награду

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#48]
**Опишите баг**
Есть информация в чате о награде, но не встроена сама награда в кейс
![photo_2024-09-08 14 52 23](https://github.com/user-attachments/assets/a81fed09-842f-4faf-bb8e-256db94a04c3)

**Comment by DraimCiDo** [comment]
Исправлены команды на выдачу.
