### ISSUE TITLE
[Баг] Выпадение 4 яиц вместо 1 в Кейсе с Яйцами

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#50]
**Опишите баг**
При открытии кейса выпадает 4 Яйца Существа, вместо 1. Выпадение 4 крутых яиц слишком сильно разовьет игрока и игрок быстрее добьется всего на сервере и потеряет к нему интерес

**Ожидаемый исход**
Уменьшить кол-во до 1, дабы не рушить кейсом экономическую сторону сервера

**Comment by DraimCiDo** [comment]
Исправлено.
