### ISSUE TITLE
[Баг] Vegas(Casino plugin) Не работает от слова совсем

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#52]
**Опишите баг**
Ошибка при запуске, 0 рабочих команд
**Ожидаемый исход**
Обновить плагин до новой версии (Новая версия имеет поддержку 1.21, так что особых проблем не возникнет)
https://www.spigotmc.org/resources/vegas-⭐-casino-plugin-►-16-game-modes-1-12-1-21-1.92321/

**Comment by DraimCiDo** [comment]
Плагин полноценно работает.
![image](https://github.com/user-attachments/assets/45ebb3ba-0b71-41ec-95f1-0f618f175f7b)
Команда /vegas, а так же в меню путеводителя.
