### ISSUE TITLE
[Нововведение] Отключение Фантомов

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#53]
**Опишите что бы вы хотели добавить**
Просто, быстро, но игроки скажут спасибо. Вместо самих фантомов добавить в магазин сервера их мембраны за небольшую цену

**Comment by DraimCiDo** [comment]
Спавн фантомов отключен

**Comment by DraimCiDo** [comment]
Для добавление мембран, требуется реализовать магазин сервера - #59

**Comment by DraimCiDo** [comment]
Мембраны добавлены в магазин сервера.
