### ISSUE TITLE
[Нововведение] Автоматическая продажа серверу накопленных с Донат кейс привилегий

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#54]
**Опишите что бы вы хотели добавить**
Кроме накопления привилегий с донат кейс с целью продажи их игрокам, предлагается через отдельную меню сделать автопродажу накопленной привилегии серверу за 20% от реальной стоимости привилегии на сайте по курсу 1 рубль - 1 квинт

**Comment by DraimCiDo** [comment]
Перенесено в https://github.com/Server-Eclipse/Website/issues/1
