### ISSUE TITLE
[Нововведение] Удобное меню для переключения основных флагов Региона

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#56]
**Опишите что бы вы хотели добавить**
Меню по команде /flags для переключения С помощью Лкм/Пкм Основных флагов(ПВП, entry, chest-acces, fall damage,damage animals, chorus fruit teleportation) 

**Скриншоты**
<img width="1710" alt="Снимок экрана 2024-09-08 в 15 20 00" src="https://github.com/user-attachments/assets/443d6ecd-5297-4e47-84dd-d187d962097e">

**Comment by DraimCiDo** [comment]
![Image](https://github.com/user-attachments/assets/5bf44631-7ab1-4842-aea9-b1f028272148)
Готово
