### ISSUE TITLE
[Баг] Пулл нерабочих команд/отсутсвующих меню 

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#57]
**Опишите баг**
Не работают следующие команды:
/marry - сделать меню для /marry
/warps и /warp - нет меню/не пашет плагин Player warps
/donshop - отсутствует, хотя был
/tops (top) - Топы по статистикам отсутствуют, хотя были
/obmen - отсутствует, хотя был
/doplata - отсутствует, хотя был
/kits (kit) - Нужна отдельная меню (Не встроенная от cmi)
/help - отсутствует, хотя был
/seller - (Выставляешь предмет, но купить нельзя)
/qs help - не выдает список доступных команд

**Ожидаемый исход**
Вернуть/Доделать/Сделать данные менюшки

**Comment by DraimCiDo** [comment]
Плагин PlayerWarps перешел в Premium категорию, у меня данного плагина нет.

**Comment by DraimCiDo** [comment]
/donshop является командой /dshop, добавлена в качестве альтернативы.

**Comment by DraimCiDo** [comment]
Команда /top является отключенной, т.к. на спавне имеется размещение голограмм с топами.

**Comment by DraimCiDo** [comment]
Команда /obmen является отключенной, т.к. на сервере больше нет плагина на косметику, он вызывал зависания и подлагивание режима. (Покрайней мере на новом ядре)
А т.е. данной команда является бесполезной.

**Comment by DraimCiDo** [comment]
Команда /doplata является отключенной, т.к. вся доплата будет реализована на веб-сайте проекта.

**Comment by DraimCiDo** [comment]
Команда /kits - уже реализовано кастомное меню...

![Image](https://github.com/user-attachments/assets/7ec9e487-859a-4995-833d-c55f0915c97b)

**Comment by DraimCiDo** [comment]
Команда /help присвоенна как альтернативная команде /menu

**Comment by DraimCiDo** [comment]
Команда /seller является - механикой СКУПЩИК, т.е. по названию понятно что он только покупает предметы, но некоторые уникальные предметы можно у него купить

![Image](https://github.com/user-attachments/assets/f39e65c2-3d19-4a1a-9e34-12b914a21669)

**Comment by DraimCiDo** [comment]
Команда /qs help отключена, т.к. данного плагина нету, он является вопервых устарвшим, вовторых малоиспользуемый из-за трейдов, скупщика, магазина сервера.
