### ISSUE TITLE
[Баг] Не Работает плагин Duels

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#58]
**Опишите баг**
При вводе /duel и прочих команд отвечает ошибкой

**Ожидаемый исход**
Переустановить, Попытаться вернуть к жизни. (Плагин древнерусский, но работать вроде может на новых версиях. Официально поддерживает лишь до 1.19, но стабильно работал и на 1.20.1 и 1.20.4)
https://www.spigotmc.org/resources/duels.20171/

**Comment by DraimCiDo** [comment]
Исходя из Баг-репортов плагина, он не работает на 1.21+, но у него открытый исходный код, попробую изменить его и добавить поддержку.

**Comment by DraimCiDo** [comment]
Обновление https://github.com/DraimCiDo/Duels/commit/fefe60486bfc3672c671f850ac8c31f01c92c9b4
Очень крупное, очень жирное обновление плагина.

![Image](https://github.com/user-attachments/assets/106fbdf5-9309-48b1-847e-73febc730295)
Плагин успешно запущен.
