### ISSUE TITLE
[Нововведение] Замена наград донат кейса 

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#61]
**Опишите что бы вы хотели добавить**
Временные донаты немного не вписываются в концепцию проекта. Можно добавить в кейс постоянные привилегии, но с малым шансом и оставить временные(7 дней) с шансом побольше

**Comment by DraimCiDo** [comment]
Сделаны для каждой выпадаемой привилегии призы - навсегда с маленькими шансами.
