### ISSUE TITLE
[Баг] некорректное отображение наград Донат кейса

### ISSUE THREAD

**Issue by Sfirut** [Server-Eclipse/Survival#62]
**Опишите баг**
Не работает цветовой код при анимации прокрутки кейса

**Ожидаемый исход**
убрать, заменить цветовой код на рабочий.

**Скриншоты**
![IMG_20240910_232850_090](https://github.com/user-attachments/assets/caa6acc3-b92b-4933-ae08-429e5f10c767)

**Comment by DraimCiDo** [comment]
Исправлено.
