### ISSUE TITLE
[Нововведение] Brewery

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#63]
Плагин добавляет на сервер алкоголь .
BreweryNG — это плагин, добавляющий в альтернативную систему пивоварения , вина и всех видом алкоголя дополняющую систему  новыми процессами, напоминающими реальное варение.

**Как вы бы хотели его видеть?**
Четкое и краткое описание того, что, по вашим ожиданиям, должен он делать.

**Ссылка на плагин**
https://modrinth.com/plugin/breweryng

**Comment by DraimCiDo** [comment]
Последняя поддерживая версия плагина 1.19.
