### ISSUE TITLE
[Нововведение] /flags

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#65]
**Опишите что бы вы хотели добавить**
Команда которая помогает включить/отключить флаги в своем регионе.

**Как вы бы хотели его видеть?**

[Player] 
-Урон по мирным мобам 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить наносить урон по мирным мобам , находящимся  в вашем регионе .

[Player]
-ПВП в Регионе 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить игрокам наносить урон другим игрокам , находящимся в вашем регионе .

[Player]
-Гриф Эндерменом 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить эндермену ставить или ломать блоки , находящиеся в вашем регионе . 

[Player]
-Доступ к сундукам 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить игрокам иметь доступ к вашим сундукам , находящиеся в вашем регионе .

[Amako | Date]
-Плод хоруса в регионе | Эндер-Жемчуг в регионе 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить игрокам использовать плод хоруса в вашем регионе | Запретить или разрешить игрокам использовать Эндер-Жемчуг  находящимся  вашем регионе . 

[Mogami]
-Взаимодействие в Регионе
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить игрокам использовать (Кнопки , двери ,рычаги , механизмы и тд . находящимся в вашем регионе .

[Asai]
-Поднятие предметов 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить игрокам поднятие предметов в регионе . 

[Takeda]
-Урон от падения в Регионе 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить игрокам получать урон от падения находящимся в вашем регионе .

[Urakami | Moishe | Satomi]
-Транспорт в Регионе 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить игрокам размещать транспорт в вашем регионе . 

[Shinobi]
-Вход в Регион 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить игрокам входить в ваш регион .

[Samurai] 
-Спавн мобов в Регионе 
Статус : Включен | Выключен | Не установлен .
>Данный флаг дает возможность : Запретить или разрешить спавн мобов в вашем регионе . 

![Screenshot_4](https://github.com/user-attachments/assets/394c9eda-6f9d-45ab-8462-bcb740a55535)

![Screenshot_1](https://github.com/user-attachments/assets/34e11873-ffa5-46dd-9bcb-a06468037e82)

**Comment by DraimCiDo** [comment]
Является дупликатом #56
