### ISSUE TITLE
[Нововведение] Сортировка сундуков 

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#66]
**Опишите что бы вы хотели добавить**
/chestsort 

**Как вы бы хотели его видеть?**
Команда /chestsort отвечает за отключение | включение автоматической сортировки в сундуках . 

**Скриншоты**
![Screenshot_1](https://github.com/user-attachments/assets/1444d17e-ad6a-46dc-b574-6bc87a9b695c)

![Screenshot_2](https://github.com/user-attachments/assets/004f6713-ec95-4e61-8d2d-52910978eca8)

![Screenshot_3](https://github.com/user-attachments/assets/58da1f99-19f0-4cbd-97ab-1fd2a4365561)

![Screenshot_4](https://github.com/user-attachments/assets/1ab14568-1216-472f-83e2-2d5ddaa7d6a3)

**Comment by DraimCiDo** [comment]
- [x] Плагин установлен

**Comment by DraimCiDo** [comment]
Ready
