### ISSUE TITLE
[Нововведение] Клан

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#67]
**Опишите что бы вы хотели добавить**
Отображаемая информация о клане 

**Как вы бы хотели его видеть?**
При наведение курсора на клан в чате показывается полная информация 

**Скриншоты**
![Screenshot_5](https://github.com/user-attachments/assets/67fe4b8d-06ec-42b4-a0f5-e045a1833ce2)

**Comment by DraimCiDo** [comment]
![Image](https://github.com/user-attachments/assets/58353baa-775b-4252-9513-c2fac05a9b96)
Готово
