### ISSUE TITLE
[Нововведение] Отображение информации про игрока 

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#68]
**Как вы бы хотели его видеть?**
При наведении курсора на ник игрока отображается полная информация об игроке . При нажатии (Клик для взаимодействия )
Появляется кликабельная  плашка [Телепорт] [Сообщение] [Обмен] [Дуэль] 

**Скриншоты**
![Screenshot_1](https://github.com/user-attachments/assets/ce427b44-f883-476e-a177-a0bc4aca206b)

![Screenshot_2](https://github.com/user-attachments/assets/bb7ffce4-6b45-4892-ab2d-004154dfe83b)

**Comment by DraimCiDo** [comment]
Реализована система кнопок
![Image](https://github.com/user-attachments/assets/e9a5474b-4665-44f5-919a-14e59c085f4d)

**Comment by DraimCiDo** [comment]
Но появился баг, никнейм черным цветом отображается, требуется исправить

**Comment by DraimCiDo** [comment]
Все исправлено и работает.
