### ISSUE TITLE
[Нововведение] Rewards

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#69]
**Опишите что бы вы хотели добавить**
Команда /rewards
C привилегии [Satomi]

**Как вы бы хотели его видеть?**
При вписывании команды /rewards можно подарить | Продать любую выпавшую привилегию с Донат кейса 
Продать имеется в виду серверу ну либо же игроку . 

**Скриншоты**
Продажа серверу указана на срине . Каждая привилегия повышается с ценой ....

![Screenshot_1](https://github.com/user-attachments/assets/0b2b39c1-3d78-48fb-8ceb-a2d8bf4b47a9)

**Дополнительный контекст**
Добавьте сюда любые другие сведения о нововведение.

**Comment by DraimCiDo** [comment]
Дупликат к #54
