### ISSUE TITLE
[Нововведение] Обновить Аукцион 

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#73]
**Как вы бы хотели его видеть?**
Ну как-то более красочней...

**Скриншоты**
![Screenshot_1](https://github.com/user-attachments/assets/057fafcf-a081-43bb-aec1-b12baaece127)
![2](https://github.com/user-attachments/assets/3aad6e3a-9976-4c43-b415-a16ea26c2b91)
![3](https://github.com/user-attachments/assets/79a86359-b261-4473-8ff2-21edfb5894e6)
![4](https://github.com/user-attachments/assets/49129a54-4705-42e2-87d6-ff6e7b4a791f)
![5](https://github.com/user-attachments/assets/61fd3f3f-a2dc-40f9-8866-37cff32799fa)
![6](https://github.com/user-attachments/assets/ce2b8005-2ed3-45f4-bd81-723327331e6c)
![7](https://github.com/user-attachments/assets/b16f89e4-9d74-4a8e-9637-3b7db013fa64)
![8](https://github.com/user-attachments/assets/6dc9336d-b794-4dcb-b2ef-69d41ea59d39)

**Comment by DraimCiDo** [comment]
- Весь текст выровнен. 
- Исправлены некорректное отображение кнопок.
- Изменена вся цветовая палитра кнопок.
