### ISSUE TITLE
[Нововведение] Плагин отвечающий за Лифт по табличкам 

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#75]
**Опишите что бы вы хотели добавить**
[SURV]
Лифт помогающий передвигаться игрокам между блоками благодаря табличке 

**Как вы бы хотели его видеть?**
Просто поместите табличку на стену или на землю и напишите [Поднять вверх], [Поднять вниз] или просто [Поднять].
**Ссылка на плагин**
[Плагин](#)

**Ссылка**
https://modrinth.com/plugin/mobis-elevator-signs
На версию 1.21

![Screenshot_1](https://github.com/user-attachments/assets/9c3416cf-931e-4c91-8edb-8aa95dbaa05c)

**Comment by DraimCiDo** [comment]
Нет надобности в добавление ещё одного плагина, у нас стоит CMI.
В нём уже есть этот функционал, пример:
[GIF](https://www.zrips.net/wp-content/uploads/2019/02/2019-02-21_12-07-34.gif)

[Документация](https://www.zrips.net/cmi/extra/elevator/)
