### ISSUE TITLE
[Нововведение] Привилегии 

### ISSUE THREAD

**Issue by PSIX0021** [Server-Eclipse/Survival#81]
[**Amako**]
>/kit Amako каждые 14 дней 
>/loom (Ткацкий станок)
>/grindstone (Точильный камень)
>/hat (Надеть предмет на голову)
>/join (Сообщение о входе)
 
   Дополнительные возможности 
-Префекс в чате и табе  [Amako] 
-[20] слотов на аукционе , [5] точек дома 
-[5] регионов привата по (400.000) блоков 
-Флаг [Эндер-Жемчуг] в /flags
-[4] работы в /jobs
-Авто-выдача денег раз  в 30 минут [10$]

[**Date**]
>/kit Date каждые 14 дней 
>/seen ник игрока (Узнать когда игрок был в сети)
>/options (Отключить ТП к себе)
>/anvil  (Открыть наковальню)
>/ctable (Открыть стол картографа) 
>/stable (Открыть стол кузнеца)
>/sc (Открыть камнерез) 

    Дополнительные возможности 
-Префикс  в чате и табе [Date]
-[25] слотов на аукционе, [8] точек дома     
-[10] регионов привата по (500.000) блоков 
-[5] работ в /jobs
-Флаг [Плод-Хоруса]  в /flags
-Авто-выдача денег раз  в 30 минут [20$]
-Возможности предыдущего доната ,кроме /kit 

[**Mogami**]
>/kit Mogami каждые 14 дней 
>/ptime (Установить личное время)
>/pweather (Установить личную погоду)
>/ec (Эндер сундук)
>/ext (Потушить себя)
>/clan create (Создать свой клан)
----------------------------Добавить /craft 
    Дополнительные возможности 
- Префикс в чате и табе [Mogami]
-[30] слотов на аукионе , [10] точек дома 
-[15] регионов привата по (600.000) блоков 
-[6] работ  в /jobs
-Флаг (Взаимодействие)  в /flags 
-Авто-выдача денег раз  в 30 минут [30$]
-Возможности предыдущего доната ,кроме /kit 

[**Asai**]
>/kit Asai каждые 14 дней 
>/feed (Накормить себя)
>/near (Найти игроков рядом)
>/dback (Вернуться на место смерти)
>/notarget (Стать незаметным для мобов)
>/sun /rain /storm (Изменить погоду в мире)
>/warp set (Создать свой варп) 

   Дополнительные возможности 
- Префикс в чате и табе [Asai]   
-[35] слотов на аукционе , [12] точек дома 
-[20] регионов привата по (700.000) блоков 
-[8] работ в /jobs
-[1] варп доступен для создания 
-Флаг (Поднятие Предметов) в /flags 
-Авто-выдача денег раз  в 30 минут [40$]
-Возможности предыдущего доната ,кроме /kit 

[**Takeda**]
>/kit Takeda каждые 14 дней 
>/heal (Вылечить себя)
>/repair (Починить вещь в руке)
>/expfly (Полет за опыт)
>/flyc (Выключить временный полет)
>/itemname (Дать название предмету)
>/itemlore (Дать описание предмету)
>/day /night (Изменить время в мире) 
>/chatcolor (Цвет сообщения в чате)

    Дополнительные возможности 
- Префикс в чате и табе [Takeda]
-Написание цветным текстом в чате /colors 
-[40] слотов на аукционе , [14] точек дома 
-[25] регионов привата по (800.000) блоков 
-[10] работ в /jobs 
-[2] варпа доступно для создания 
-Флаг (Урон от падения ) в /flags 
-Авто-выдача денег раз  в 30 минут [50$]
-Возможности предыдущего доната ,кроме /kit 

[**Urakami**]
>/kit Urakami каждые 14 дней 
>/mfly сумма (Полет за деньги)
>/flycharge - 50% скидка на заряд полёта)
>/ec ник (Посмотреть чужой эндер сундук) 
>/invsee ник (Посмотреть чужой инвентарь)
>/feed ник (Накормить другого игрока)
>/rewards (Выдать донат игроку из кейса)

    Дополнительные возможности 
-Префикс в чате и табе [Urakami]
-Написание курсивным цветом в чате /colors
-Написание цветным текстом на табличках 
-[45] слотов на аукционе , [16] точек дома 
-[35] регионов привата (1.500.000) блоков 
-[3] варпа доступно для создания 
-Флаг (Размещение транспорта) в /flags 
-Авто-выдача денег раз  в 30 минут [60$]
-Возможности предыдущего доната ,кроме /kit 

[**Satomi**] 
>/kit Satomi каждые 14 дней
>//limit (1000-10000) - установить свой личный лимит на команды WorldEdit 
>//set (матерьял) - заполнить выделенную территорию блоком
>//walls (матерьял) - сделать стены из блока
>//sphere (радиус) (матерьял) - заполнить выделенную территорию блоком/
>//replace (матерьял) (матерьял) - заменить один тип блока другим
>/fly (Бесплатный полет)
>/flyspeed (0-3) - изменить свою скорость полета
>/cplaytime (игрок) - просмотреть своё или игрока время на сервере
>/heal ник (Вылечить игрока)
>/repair all (Починить все вещи в инвентаре)
>/bc (Сделать объявление для всех)
>/glow (Включить подсветку персонажа)
>/back (Вернуться в последнее сохраненное место)
>/mirror [start | stop] (Зеркальные постройки)

  Дополнительные возможности 
-Префикс в чате и табе [Satomi]
-Выпадение спавнера с шансом 10%
-Написание ЖИРНЫМ шрифтом текстом в чате /colors
-[60] слотов на аукционе , [20] точек дома ff
-[50] регионов привата по (2.500.000) блоков 
-[4] варпа доступно для создания 
-Флаг (Вход в регион) в /flags 
-Создать (ЛИФТ) [ЛИФТ] на табличке 
-Авто-выдача денег раз  в 30 минут [70$]
-Возможности предыдущего доната ,кроме /kit 

[**Shinobi**]
>/kit Shinobi каждые 14 дней 
>/god (режим бессмертия)
>//limit (5000-50000) - установить свой личный лимит на команды WorldEdit
>/flyspeed (0-5) - изменить свою скорость полёта
>/walkspeed (0-3) - изменить свою скорость ходьбы 
>/head (выдать голову игрока)
>/top (телепортироваться на уровень выше)
>/down (телепортироваться на уровень ниже)
>/bm (объявление в босcбаре)
>/psize (изменить размер тела)
>/ride - возможность прокатиться на друге
>/armorstand (flast/near) - расширенное управление стойками для брони

   Дополнительные возможности 
-Префикс в чате и табе [Shinobi]
-Выпадение спавнера с шансом 15%
-[70] слотов на аукционе , [30] точек дома
-[70] регионов привата по (3.500.000) блоков
-[6] варпа доступно для создания 
-Флаг (Спавн-Мобов) в /flags
-Авто-выдача денег раз  в 30 минут [80$]
-Возможности предыдущего доната ,кроме /kit 

[**Samurai**]
>/kit Samurai каждые 14 дней
>/prefix (изменить цвет префикса)
>/save on/off (сохранение предметов после смерти)
>/vanish (режим невидимки)
>/flyspeed (изменить скорость полета от 1 до 7) 
>/walkspeed (изменить скорость ходьбы от 1 до 4) 
>//limit (-1) - установить лимит на команды WorldEdit
>/feed all (накормить всех)
>/heal all (вылечить всех)
>/clear (очистить инвентарь)
>/givefly (ник) - выдает полет выбранному игроку на 2 часа (кд - 2дня)

    Дополнительные возможности 
-Префикс в чате и табе [Samurai]
-Выпадение спавнера с шансом 20%
-[100] слотов на аукционе , [50] точек дома 
-[90] регионов привата по (4.000.000) блоков 
-[7] варпов для создания 
-Полный доспуп к флагам 
-Полный доступ к WorldEdit
-Лимит на //set безграничный
-Авто-выдача денег раз  в 30 минут [100$]
-Возможности предыдущего доната ,кроме /kit

**Comment by DraimCiDo** [comment]
@Armagidosha данная информация так же полезна для разработки https://github.com/Server-Eclipse/Website

**Comment by DraimCiDo** [comment]
Переработаны некоторые права донатов, которые тут прописаны.
